/**
 * 畫面文字的字串表（三種語言）：zh 全中文版、en 英文版、ja 日文版。
 * - 日文版是原本的日式熱血風格：標題、橫幅等大字是日文或英文，說明文字是中文。
 *   所以 ja 只寫日文版和中文版不同的字；沒寫 ja 的字，日文版顯示 zh（見 src/i18n.ts 的 tr）。
 * - {name} 是要代入的參數。
 * - 英文版不可以出現中日文字（tests/i18n.test.ts 檢查）；中文版不可以有假名，英文只限按鍵名稱與「Go Shoot」。
 * 這個檔不碰 window／document，單元測試（Node）可以直接載入。
 */

/** 一句字串：中文、英文必填，日文版和中文版不同時才填 ja */
export interface TextEntry {
  zh: string;
  en: string;
  ja?: string;
}

export const TEXT = {
  // ---------------- 標題畫面 ----------------
  'doc.title': { ja: 'Battle Tops', zh: '戰鬥陀螺', en: 'Battle Tops' },
  'title.logo': { ja: 'BATTLE TOPS', zh: '戰鬥陀螺', en: 'BATTLE TOPS' },
  'title.sub': { ja: '爆転バトル ・ 戰鬥陀螺', zh: '爆轉對戰', en: 'Burst Spin Battle' },
  'title.start': { ja: 'CPU 対戦 ／ 電腦對戰', zh: '電腦對戰', en: 'VS CPU' },
  'title.trial': { ja: 'トライアル ／ 試驗模式', zh: '試驗模式', en: 'Trial Mode' },
  'title.online': { ja: 'オンライン対戦 ／ 線上對戰（找朋友）', zh: '線上對戰（找朋友）', en: 'Online with Friends' },
  'title.tutorial': { ja: 'チュートリアル ／ 操作教學', zh: '操作教學', en: 'Tutorial' },
  'title.langAria': { zh: '語言', en: 'Language' },
  'title.offer': { zh: '第一次玩？建議先看操作教學（約 3 分鐘）', en: 'First time? Try the tutorial first (about 3 min)' },
  'title.offerGo': { zh: '開始教學', en: 'Start Tutorial' },
  'title.offerNo': { zh: '不用了', en: 'No Thanks' },
  'title.note': { zh: '請開啟聲音（建議戴耳機，3D 立體音效）', en: 'Turn on sound (headphones recommended for 3D audio)' },
  'title.rotate': { zh: '📱 橫向遊玩效果較好', en: '📱 Best played in landscape' },
  'audio.hint': { ja: '🔊 クリックで音声ON／點擊畫面開啟聲音', zh: '🔊 點擊畫面開啟聲音', en: '🔊 Click to turn on sound' },
  'webgl.none': {
    zh: '這個瀏覽器環境沒有 WebGL，無法顯示 3D 畫面。請改用 Chrome／Edge 並開啟硬體加速。',
    en: "This browser doesn't support WebGL, so the 3D view can't be shown. Please use Chrome or Edge with hardware acceleration turned on.",
  },

  // ---------------- 組隊第 1 步 ----------------
  'select.title': { ja: 'チームを組め！', zh: '組成隊伍！', en: 'Build Your Team!' },
  'select.step': {
    zh: '第 1 步：選場地與三顆陀螺（點選順序是預設的出場順序，下一步可以調整順序與零件）',
    // 手機橫向的組隊畫面只放得下一行（換行會把「Next」擠出畫面），英文寫短一點
    en: 'Step 1: Pick a stadium and 3 tops (pick order = battle order)',
  },
  'select.keysKb': {
    zh: '（方向鍵移動、Space 選取／取消、Enter 下一步、1／2／3 難度、Q／E 場地）',
    en: ' (Arrows: move · Space: pick/unpick · Enter: next · 1/2/3: difficulty · Q/E: stadium)',
  },
  'select.keysTc': { zh: '（點小格選取／取消）', en: ' (Tap to pick/unpick)' },
  'select.cpuTeam': { ja: 'CPU チーム', zh: '電腦隊伍', en: 'CPU Team' },
  'select.cpuNote': { zh: '出場順序保密', en: 'Order hidden' },
  'select.next': { zh: '下一步 ▶', en: 'Next ▶' },
  'diff.aria': { zh: '難易度', en: 'Difficulty' },
  'diff.easy': { ja: 'かんたん', zh: '簡單', en: 'Easy' },
  'diff.normal': { ja: 'ふつう', zh: '普通', en: 'Normal' },
  'diff.hard': { ja: 'むずかしい', zh: '困難', en: 'Hard' },
  'arena.aria': { zh: '場地', en: 'Stadium' },
  'arena.random': { zh: '隨機', en: 'Random' },
  'arena.randomDesc': { zh: '開打時從六個場地隨機抽一個。', en: 'One of the six stadiums is drawn at random when the battle starts.' },
  'arena.randomPick': { zh: '隨機（開打時抽）', en: 'Random (drawn at start)' },

  // ---------------- 陀螺的說明（卡片、名鑑、詳細資料） ----------------
  'type.attack': { zh: '攻擊型', en: 'Attack' },
  'type.defense': { zh: '防禦型', en: 'Defense' },
  'type.stamina': { zh: '持久型', en: 'Stamina' },
  'type.balance': { zh: '平衡型', en: 'Balance' },
  // 名鑑小格角落的類型字（一個字）
  'type.attack.s': { zh: '攻', en: 'A' },
  'type.defense.s': { zh: '防', en: 'D' },
  'type.stamina.s': { zh: '持', en: 'S' },
  'type.balance.s': { zh: '平', en: 'B' },
  'tile.left': { zh: '左', en: 'L' },
  'tile.title': { zh: '{name}（{type}）', en: '{name} ({type})' },
  'spin.right': { zh: '右旋', en: 'Right spin' },
  'spin.left': { zh: '左旋', en: 'Left spin' },
  'spin.switch': { zh: '（可切換）', en: ' (switchable)' },
  // 六項屬性：完整名稱、雷達圖與卡片的短名稱、零件清單小膠囊的一個字
  'stat.attack': { zh: '攻擊', en: 'Attack' },
  'stat.defense': { zh: '防禦', en: 'Defense' },
  'stat.stamina': { zh: '持久', en: 'Stamina' },
  'stat.weight': { zh: '重量', en: 'Weight' },
  'stat.burst': { zh: '爆裂抵抗', en: 'Burst Res.' },
  'stat.dash': { zh: '機動', en: 'Dash' },
  'stat.attack.s': { zh: '攻擊', en: 'ATK' },
  'stat.defense.s': { zh: '防禦', en: 'DEF' },
  'stat.stamina.s': { zh: '持久', en: 'STA' },
  'stat.weight.s': { zh: '重量', en: 'WT' },
  'stat.burst.s': { zh: '爆裂', en: 'BUR' },
  'stat.dash.s': { zh: '機動', en: 'DSH' },
  'stat.attack.t': { zh: '攻', en: 'ATK' },
  'stat.defense.t': { zh: '防', en: 'DEF' },
  'stat.stamina.t': { zh: '持', en: 'STA' },
  'stat.weight.t': { zh: '重', en: 'WT' },
  'stat.burst.t': { zh: '爆', en: 'BUR' },
  'stat.dash.t': { zh: '機', en: 'DSH' },
  'charge.fast': { zh: '快', en: 'fast' },
  'charge.mid': { zh: '中', en: 'medium' },
  'charge.slow': { zh: '慢', en: 'slow' },
  'charge.label': { zh: '集氣 {tier}（約 {c} 秒）', en: 'Special charge: {tier} (about {c} s)' },
  'card.special': { zh: '必殺：{name}', en: 'Special: {name}' },
  // 日文版的詳細資料：日文必殺名後面附中文名
  'card.specialWithZh': { zh: '必殺：{name}（{zh}）', en: 'Special: {name}' },
  'detail.stage': { zh: '外觀・絕招示範', en: 'Look · Special Move Demo' },
  'detail.origin': { zh: '原型：{name}', en: 'Based on: {name}' },
  'detail.original': { zh: '原創', en: 'Original' },
  'detail.part': { zh: '{slot}：{name}（{code}）', en: '{slot}: {name} ({code})' },
  'detail.stock': { zh: '・原廠', en: ' · stock' },

  // ---------------- 零件 ----------------
  'slot.disk': { zh: '盤', en: 'Disk' },
  'slot.driver': { zh: '軸', en: 'Driver' },
  'part.stock': { zh: '原廠', en: 'Stock' },
  'part.current': { zh: '使用中', en: 'Equipped' },
  'part.menuHead': { zh: '換{slot}：{name}', en: 'Change {slot}: {name}' },
  'part.option': { zh: '{name}（{code}）', en: '{name} ({code})' },
  'part.takenBy': { zh: '裝在{name}（備用零件每種一件）', en: 'On {name} (only one of each spare part)' },
  'part.aria': { zh: '換{slot}（目前：{name}（{code}）{stock}）', en: 'Change {slot} (current: {name} ({code}){stock})' },
  'part.ariaStock': { zh: '，原廠', en: ', stock' },

  // ---------------- 組隊第 2 步 ----------------
  'arrange.title': { ja: '出場順と部品', zh: '出場順序與零件', en: 'Order & Parts' },
  'arrange.step': { zh: '第 2 步：調整出場順序與零件，第 1 戰先上場', en: 'Step 2: Set the battle order and parts (No. 1 battles first)' },
  'arrange.keysKb': {
    zh: '（↑↓ 選擇、Shift＋↑↓ 調換順序、Q／E 換盤／軸、Enter 確定）',
    en: ' (↑↓: select · Shift+↑↓: reorder · Q/E: change disk/driver · Enter: confirm)',
  },
  'arrange.keysTc': { zh: '（點「盤」「軸」換零件，▲▼ 調換順序）', en: ' (Tap Disk/Driver to change parts, ▲▼ to reorder)' },
  'arrange.back': { zh: '◀ 回上一步', en: '◀ Back' },
  'arrange.ready': { zh: '出陣！', en: 'Battle!' },
  'arrange.readyOnline': { zh: '準備完成', en: 'Ready' },
  'arrange.arena': { zh: '場地：{name}', en: 'Stadium: {name}' },
  'arrange.n': { zh: '第 {n} 戰', en: 'No. {n}' },
  'arrange.up': { zh: '往前一戰', en: 'Move one battle earlier' },
  'arrange.down': { zh: '往後一戰', en: 'Move one battle later' },
  'arrange.left': { zh: '剩 {n} 秒', en: '{n} s left' },
  'arrange.timeUp': { zh: '時間到', en: "Time's up" },
  'arrange.timeUpLock': { zh: '時間到，用目前的順序與零件開戰…', en: "Time's up! Battling with the current order and parts…" },
  'arrange.waitOpp': { zh: '已準備完成，等待對手…', en: 'Ready! Waiting for your opponent…' },

  // ---------------- 對手（CPU 與線上） ----------------
  'opp.default': { zh: '對手', en: 'Opponent' },
  'opp.label': { zh: '對手：{name}', en: 'Opponent: {name}' },
  'opp.choosing': { zh: '選擇中…', en: 'Choosing…' },
  'opp.left': { zh: '離開了', en: 'Left' },
  'opp.disconnected': { zh: '連線中斷…', en: 'Disconnected…' },
  'opp.picked': { zh: '已選好三顆', en: 'Picked three tops' },
  'opp.ready': { zh: '準備完成 ✓', en: 'Ready ✓' },
  'opp.adjusting': { zh: '調整中…', en: 'Adjusting…' },

  // ---------------- 試驗模式 ----------------
  'trial.title': { ja: 'トライアル', zh: '試驗模式', en: 'Trial' },
  'trial.step': { zh: '試驗模式：一對一，自己挑雙方的陀螺與零件，比較搭配的效果', en: 'Trial: one on one. Pick both tops and their parts to compare setups' },
  'trial.keysKb': {
    zh: '（點「你」或「電腦」再點名鑑換陀螺；方向鍵移動、Space 換上、X 切換你／電腦、Enter 開始、1／2／3 難度、Q／E 場地）',
    en: ' (Click YOU or CPU, then a top in the list to swap it in · Arrows: move · Space: swap in · X: switch YOU/CPU · Enter: start · 1/2/3: difficulty · Q/E: stadium)',
  },
  'trial.keysTc': { zh: '（點「你」或「電腦」，再點名鑑換陀螺）', en: ' (Tap YOU or CPU, then a top in the list to swap it in)' },
  'trial.back': { zh: '◀ 回標題', en: '◀ Title' },
  'trial.go': { zh: '開始試驗 ▶', en: 'Start Trial ▶' },
  'trial.auto': { zh: '電腦自動對打 1000 場', en: 'CPU Auto-Battle ×1000' },
  'trial.stop': { zh: '停止', en: 'Stop' },
  'trial.retry': { zh: '同設定再戰', en: 'Same Setup Again' },
  'trial.change': { zh: '換設定', en: 'Change Setup' },
  'trial.clear': { zh: '清除紀錄', en: 'Clear Records' },
  'trial.toTitle': { zh: '回標題', en: 'Back to Title' },
  'trial.cpu': { zh: '電腦', en: 'CPU' },
  'trial.badgeYou': { zh: '你', en: 'P' },
  'trial.badgeCpu': { zh: '電', en: 'C' },
  'trial.info': { zh: '試驗・{arena}', en: 'TRIAL · {arena}' },
  'trial.withParts': { zh: '{name}（{parts}）', en: '{name} ({parts})' },
  'trial.partsJoin': { zh: '＋', en: ' + ' },
  'trial.autoHead': { zh: '電腦自動對打', en: 'CPU Auto-Battle' },
  'trial.draw': { zh: '平手', en: 'Draw' },
  'trial.matchup': { zh: '{you}：{p} {vs} 電腦：{c}＠{arena}・{diff}', en: '{you}: {p} {vs} CPU: {c} @ {arena} · {diff}' },
  'trial.finish': { zh: '終結方式', en: 'Finish' },
  'trial.finishVal': { zh: '{finish}（{who}）', en: '{finish} ({who})' },
  'trial.youWin': { zh: '{you} 獲勝', en: '{you} won' },
  'trial.cpuWin': { zh: '電腦獲勝', en: 'CPU won' },
  'trial.time': { zh: '對戰時間', en: 'Battle time' },
  'trial.rpm': { zh: '剩餘轉速', en: 'Spin left' },
  'trial.burst': { zh: '爆裂值', en: 'Burst' },
  'trial.launch': { zh: '發射力道', en: 'Launch power' },
  'trial.special': { zh: '必殺', en: 'Special' },
  'trial.used': { zh: '有放出', en: 'Used' },
  'trial.unused': { zh: '沒放', en: 'Not used' },
  'trial.clash': { zh: '撞擊', en: 'Clashes' },
  'trial.clashVal': { zh: '{n} 次（重擊 {big} 次）', en: '{n} ({big} heavy)' },
  'trial.noRecord': { zh: '這組設定還沒有實際對戰紀錄。', en: 'No battles played with this setup yet.' },
  'trial.recordSum': {
    zh: '這組設定累計 {games} 戰：{w} 勝 {l} 敗 {d} 平（勝率 {rate}%）',
    en: 'This setup: {games} battles, {w} W / {l} L / {d} D (win rate {rate}%)',
  },
  'trial.youN': { zh: '你 {n}', en: 'YOU {n}' },
  'trial.cpuN': { zh: '電腦 {n}', en: 'CPU {n}' },
  'trial.autoDone': { zh: '電腦自動對打 {n} 場（雙方都由電腦操作，座位各半）', en: 'CPU auto-battle: {n} games (the CPU plays both sides, swapping seats halfway)' },
  'trial.autoRun': { zh: '電腦自動對打中… {p}%', en: 'CPU auto-battling… {p}%' },
  'trial.rate': { zh: '你的陀螺勝率 {rate}%', en: 'Your top wins {rate}%' },
  'trial.autoSum': { zh: '{w} 勝 {l} 敗 {d} 平・平均 {t} 秒', en: '{w} W / {l} L / {d} D · avg {t} s' },
  'unit.sec': { zh: '{n} 秒', en: '{n} s' },

  // ---------------- 延長賽選擇 ----------------
  'overtime.title': { ja: '延長戦！', zh: '延長賽！', en: 'Overtime!' },
  'overtime.tie': { zh: '總分平手・', en: 'Tied on points · ' },
  'overtime.sudden': { ja: 'サドンデス', zh: '驟死戰', en: 'Sudden Death' },
  'overtime.pick': { zh: '：從你的隊伍挑一顆出戰', en: ': pick one top from your team' },
  'overtime.keysKb': { zh: '（← → 移動、Enter 決定）', en: ' (← →: move · Enter: choose)' },
  'overtime.keysTc': { zh: '（點一下出戰）', en: ' (Tap to send it out)' },

  // ---------------- 對戰 HUD 與橫幅 ----------------
  'hud.rpm': { ja: 'RPM', zh: '轉/分', en: 'RPM' },
  'hud.burst': { ja: 'BURST', zh: '爆裂', en: 'BURST' },
  'hud.special': { zh: '必殺', en: 'SPECIAL' },
  'hud.readyKey': { ja: '必殺 READY ▶', zh: '必殺就緒 ▶', en: 'SPECIAL READY ▶' },
  'hud.readyTc': { zh: '按鈕／三指', en: 'Button / 3 fingers' },
  'hud.ready': { ja: '必殺 READY', zh: '必殺就緒', en: 'SPECIAL READY' },
  'hud.you': { ja: 'YOU ｜ {name}', zh: '你 ｜ {name}', en: 'YOU · {name}' },
  'hud.opp': { zh: '{name} ｜ {who}', en: '{name} · {who}' },
  'touch.ready': { ja: '必殺 READY！點右下角的按鈕（或三指觸控）', zh: '必殺就緒！點右下角的按鈕（或三指觸控）', en: 'SPECIAL READY! Tap the button at the bottom right (or tap with three fingers)' },
  'special.btn': { zh: '必殺！', en: 'SPECIAL!' },
  'special.aria': { zh: '必殺技', en: 'Special move' },
  'help.kb': { zh: 'WASD／方向鍵：推移陀螺　Shift＋方向：衝刺　SPACE：必殺技　M：音樂開關', en: 'WASD/Arrows: push · Shift+direction: dash · SPACE: special · M: music on/off' },
  'help.tc': { zh: '滑動：推移　快甩：衝刺　必殺：按鈕或三指', en: 'Swipe: push · Flick: dash · Special: button or 3 fingers' },
  you: { ja: 'YOU', zh: '你', en: 'YOU' },
  cpu: { ja: 'CPU', zh: '電腦', en: 'CPU' },
  vs: { ja: 'VS', zh: '對', en: 'VS' },
  'info.battle': { ja: 'BATTLE {n}/3', zh: '第 {n}／3 戰', en: 'BATTLE {n}/3' },
  'info.final': { ja: 'FINAL', zh: '比賽結束', en: 'FINAL' },
  'info.overtime': { zh: '延長賽', en: 'OVERTIME' },
  'info.join': { zh: '{a}・{b}', en: '{a} · {b}' },
  'banner.battle': { ja: 'BATTLE {n}', zh: '第 {n} 戰', en: 'BATTLE {n}' },
  'banner.final': { ja: 'FINAL BATTLE', zh: '最終決戰', en: 'FINAL BATTLE' },
  'banner.overtime': { ja: 'OVERTIME', zh: '延長賽', en: 'OVERTIME' },
  'banner.trial': { ja: 'TRIAL BATTLE', zh: '試驗對戰', en: 'TRIAL BATTLE' },
  'banner.replay': { ja: '（再戦）', zh: '（重賽）', en: ' (rematch)' },
  'banner.at': { zh: '＠{arena}', en: '@ {arena}' },
  // 發射的口號：台灣與日本原作一樣喊英文「Go Shoot」（全中文版唯一保留的英文遊戲用語，使用者決定）；英文版也喊 Go Shoot
  'banner.go': { ja: 'ゴー・シュート!!', zh: 'GO SHOOT!!', en: 'GO SHOOT!!' },
  'banner.shoot': { ja: 'シュート！', zh: '發射！', en: 'SHOOT!' },
  'banner.waitLaunch': { zh: '等待{name}發射…', en: 'Waiting for {name} to launch…' },
  'banner.error': { ja: 'ERROR', zh: '錯誤', en: 'ERROR' },
  'banner.draw': { ja: 'DRAW', zh: '平手', en: 'DRAW' },
  'banner.drawSub': { ja: '引き分け！もう一度！', zh: '平手！再比一次！', en: 'A draw! One more time!' },
  'banner.spin': { ja: 'SPIN FINISH!', zh: '旋轉終結！', en: 'SPIN FINISH!' },
  'banner.over': { ja: 'OVER FINISH!!', zh: '場外終結！！', en: 'OVER FINISH!!' },
  'banner.burst': { ja: 'BURST FINISH!!', zh: '爆裂終結！！', en: 'BURST FINISH!!' },
  'banner.xtreme': { ja: 'XTREME FINISH!!!', zh: '極限終結！！！', en: 'XTREME FINISH!!!' },
  'finish.spin': { ja: 'SPIN FINISH', zh: '旋轉終結', en: 'SPIN FINISH' },
  'finish.over': { ja: 'OVER FINISH', zh: '場外終結', en: 'OVER FINISH' },
  'finish.burst': { ja: 'BURST FINISH', zh: '爆裂終結', en: 'BURST FINISH' },
  'finish.xtreme': { ja: 'XTREME FINISH', zh: '極限終結', en: 'XTREME FINISH' },
  'rate.perfect': { ja: 'PERFECT!!', zh: '完美！！', en: 'PERFECT!!' },
  'rate.great': { ja: 'GREAT!', zh: '很好！', en: 'GREAT!' },
  'rate.good': { ja: 'GOOD', zh: '不錯', en: 'GOOD' },
  'rate.weak': { ja: 'WEAK…', zh: '太弱了…', en: 'WEAK…' },
  'rate.power': { ja: '{p}% POWER', zh: '力道 {p}%', en: '{p}% POWER' },
  'cutin.move': { zh: '必殺！{name}', en: 'SPECIAL! {name}' },

  // ---------------- 發射台 ----------------
  'launch.hintKb': {
    ja: '滑鼠按住往下拖（拉條），在「ゴー」的瞬間放手！左右拖可瞄準・SPACE：簡易發射（最高 85%）',
    zh: '滑鼠按住往下拖（拉條），在「Go Shoot」的瞬間放手！左右拖可瞄準・SPACE：簡易發射（最高 85%）',
    en: 'Hold the mouse and drag down (pull the cord), then let go on "Go Shoot"! Drag left/right to aim · SPACE: quick launch (up to 85%)',
  },
  'launch.hintTc': {
    ja: '手指按住往下滑（拉條），在「ゴー」的瞬間放手！左右滑可瞄準',
    zh: '手指按住往下滑（拉條），在「Go Shoot」的瞬間放手！左右滑可瞄準',
    en: 'Hold your finger and slide down (pull the cord), then let go on "Go Shoot"! Slide left/right to aim',
  },
  'launch.power': { ja: 'POWER', zh: '力道', en: 'POWER' },
  'launch.powerAim': { ja: 'POWER {p}%　{aim}', zh: '力道 {p}%　{aim}', en: 'POWER {p}%  {aim}' },
  'aim.center': { zh: '正面', en: 'straight' },
  'aim.right': { zh: '右 {n}°', en: 'right {n}°' },
  'aim.left': { zh: '左 {n}°', en: 'left {n}°' },

  // ---------------- 結果畫面 ----------------
  'result.win': { ja: 'YOU WIN!!', zh: '你贏了！！', en: 'YOU WIN!!' },
  'result.lose': { ja: 'YOU LOSE…', zh: '你輸了…', en: 'YOU LOSE…' },
  'result.retry': { ja: 'もう一度！／再來一場', zh: '再來一場！', en: 'Play Again!' },
  'result.leave': { zh: '離開', en: 'Leave' },
  'result.overtime': { zh: '延長賽', en: 'Overtime' },
  'result.battleN': { zh: '第 {n} 戰', en: 'Battle {n}' },
  'result.row': { zh: '{label}　{a} {vs} {b}　{finish}　{who} +{pts}', en: '{label} · {a} {vs} {b} · {finish} · {who} +{pts}' },
  'result.cpuFoot': { zh: '難易度：{diff}・場地：{arena}', en: 'Difficulty: {diff} · Stadium: {arena}' },
  'result.onlineFoot': { zh: '線上對戰・房號 {code}・場地：{arena}{forfeit}', en: 'Online · Room {code} · Stadium: {arena}{forfeit}' },
  'result.oppForfeit': { zh: '・對手棄權', en: ' · opponent forfeited' },
  'result.forfeit': { zh: '・判定棄權', en: ' · you forfeited' },
  'result.oppGone': { zh: '對手已離開，無法再來一場', en: 'Your opponent left, so no rematch' },
  'result.oppWants': { zh: '{name} 想再來一場', en: '{name} wants a rematch' },
  'result.waitOpp': { zh: '等待對手…', en: 'Waiting for your opponent…' },

  // ---------------- 線上對戰 ----------------
  'online.title': { ja: 'オンライン対戦', zh: '線上對戰', en: 'Online Battle' },
  'online.desc': { zh: '線上對戰：從房間列表點一下就加入，或按「快速加入」自動配對', en: 'Online: tap a room in the list to join, or press Quick Join to be matched automatically' },
  'online.name': { zh: '你的名稱', en: 'Your name' },
  'online.quick': { zh: '快速加入', en: 'Quick Join' },
  'online.create': { zh: '建立房間', en: 'Create Room' },
  'online.private': { zh: '不公開', en: 'Private' },
  'online.codePh': { zh: '房號（4 碼）', en: 'Room code (4 chars)' },
  'online.join': { zh: '加入', en: 'Join' },
  'online.rooms': { zh: '房間列表', en: 'Rooms' },
  'online.code': { zh: '房號', en: 'Room Code' },
  'online.copy': { zh: '複製連結', en: 'Copy Link' },
  'online.back': { zh: '返回', en: 'Back' },
  'online.codeLen': { zh: '房號是 4 個字（英文與數字）', en: 'Room codes are 4 characters (letters and digits)' },
  'online.copied': { zh: '已複製連結，傳給朋友開啟就能加入', en: 'Link copied. Send it to a friend to join' },
  'online.copyFail': { zh: '無法自動複製，請手動複製連結', en: "Couldn't copy automatically. Please copy the link yourself" },
  'online.noRooms': { zh: '目前沒有等人的房間：按「快速加入」會幫你開一間公開房間等人', en: 'No rooms are waiting right now. Quick Join will open a public room for you' },
  'online.randomArena': { zh: '隨機場地', en: 'Random stadium' },
  'online.newArena': { zh: '新場地', en: 'New stadium' },
  'online.playing': { zh: '對戰中', en: 'In battle' },
  'online.joinRow': { zh: '加入 ▶', en: 'Join ▶' },
  'online.waitedS': { zh: '等了 {n} 秒', en: 'waiting {n} s' },
  'online.waitedM': { zh: '等了 {n} 分鐘', en: 'waiting {n} min' },
  'online.autoRefresh': { zh: '每 3 秒自動更新', en: 'Updates every 3 s' },
  'online.waitPublic': { zh: '等待對手加入…（已列在房間列表，別人點一下就能加入）', en: 'Waiting for an opponent… (listed in the room list; anyone can tap to join)' },
  'online.waitPrivate': { zh: '等待對手加入…（不公開：把房號或連結傳給朋友）', en: 'Waiting for an opponent… (private: send the room code or link to a friend)' },
  'online.joined': { zh: '已加入，準備組隊…', en: 'Joined! Getting ready to build teams…' },
  'online.closed': { zh: '房間已關閉：{reason}', en: 'Room closed: {reason}' },
  'online.oppLeft': { zh: '對手離開了，等待新的對手加入', en: 'Your opponent left. Waiting for a new opponent' },
  'net.connecting': { zh: '連線中…', en: 'Connecting…' },
  'net.loading': { zh: '讀取中…', en: 'Loading…' },
  'net.reconnecting': { zh: '連線中斷，重新連線中…', en: 'Connection lost. Reconnecting…' },
  'net.backToRoom': { zh: '會自動回到房間', en: "You'll go back to the room automatically" },
  'net.retrying': { zh: '連不上對戰伺服器，稍後自動重試…', en: "Can't reach the battle server. Retrying shortly…" },
  'net.cantConnect': { zh: '連不上對戰伺服器，請稍後再試', en: "Can't reach the battle server. Please try again later" },
  'net.waitPick': { zh: '等待對手選好三顆…', en: 'Waiting for your opponent to pick three tops…' },
  'net.waitOvertime': { zh: '等待對手挑選延長賽的陀螺…', en: 'Waiting for your opponent to pick an overtime top…' },
  'net.oppDropped': { zh: '{name} 連線中斷', en: '{name} disconnected' },
  'net.oppDropSub': { zh: '等待重新連線… {n} 秒後判對手棄權', en: 'Waiting for them to reconnect… forfeit in {n} s' },
  // 伺服器回的錯誤（伺服器送中文訊息與錯誤碼；英文版依錯誤碼換成英文，見 src/i18n.ts 的 serverText）
  'srv.OUTDATED': {
    zh: '遊戲已更新，請重新整理頁面（電腦按 Ctrl＋F5，手機下拉重新整理）',
    en: 'The game has been updated. Please reload the page (Ctrl+F5 on a computer, pull down to refresh on a phone)',
  },
  'srv.FULL': { zh: '伺服器房間已滿，請稍後再試', en: 'The server is full right now. Please try again later' },
  'srv.NOT_FOUND': { zh: '找不到房間 {code}', en: 'Room {code} not found' },
  'srv.ROOM_FULL': { zh: '房間 {code} 已經滿了', en: 'Room {code} is already full' },
  'srv.RESUME_FAILED': { zh: '無法重新連線（房間已關閉或已過期）', en: "Couldn't reconnect (the room was closed or has expired)" },
  'srv.NOT_HOST': { zh: '只有房主能選場地', en: 'Only the host can choose the stadium' },
  'srv.unknown': { zh: '發生錯誤（{code}）', en: 'Something went wrong ({code})' },
  'srv.hostLeft': { zh: '房主離開了房間', en: 'The host left the room' },
  'srv.closed': { zh: '房間已關閉', en: 'The room was closed' },

  // ---------------- 操作教學 ----------------
  'tut.ch.team': { zh: '第 1 章　組隊', en: 'Chapter 1 · Team' },
  'tut.ch.launch': { zh: '第 2 章　發射', en: 'Chapter 2 · Launch' },
  'tut.ch.control': { zh: '第 3 章　操控', en: 'Chapter 3 · Control' },
  'tut.ch.score': { zh: '第 4 章　計分', en: 'Chapter 4 · Scoring' },
  'tut.count': { zh: '{i}／{n}', en: '{i}/{n}' },
  'tut.t.pick': { zh: '組隊：選三顆陀螺', en: 'Team: Pick Three Tops' },
  'tut.t.next': { zh: '組隊：下一步', en: 'Team: Next' },
  'tut.t.order': { zh: '調整出場順序', en: 'Battle Order' },
  'tut.t.parts': { zh: '換盤與軸', en: 'Disk & Driver' },
  'tut.t.ready': { zh: '出陣', en: 'Battle!' },
  'tut.t.launch': { zh: '拉發射台', en: 'Launch' },
  'tut.t.push': { zh: '推移陀螺', en: 'Push Your Top' },
  'tut.t.dash': { zh: '衝刺', en: 'Dash' },
  'tut.t.special': { zh: '必殺技', en: 'Special Move' },
  'tut.t.finish': { zh: '終結對手', en: 'Finish the Opponent' },
  'tut.t.points': { zh: '終結方式與得分', en: 'Finishes & Points' },
  'tut.t.match': { zh: '三對三賽制', en: '3-on-3 Match' },
  'tut.press': { zh: '按住往下拉 ⇩', en: 'Hold & pull down ⇩' },
  'tut.ram': { zh: '撞過去！', en: 'Ram it!' },
  'tut.next': { zh: '下一步 ▶', en: 'Next ▶' },
  'tut.done': { zh: '完成 ✓', en: 'Done ✓' },
  'tut.replay': { zh: '🔊 重聽', en: '🔊 Replay' },
  'tut.skip': { zh: '跳過這步', en: 'Skip Step' },
  'tut.exit': { zh: '結束教學', en: 'End Tutorial' },
  'tut.orWasd': { zh: '或 W A S D', en: 'or W A S D' },
  'tut.dashKeys': { zh: '按住方向鍵，再按一下 Shift', en: 'Hold an arrow key, then tap Shift' },
  'tut.plus': { zh: '＋', en: '+' },
  'tut.space': { zh: '空白鍵', en: 'Space bar' },
  'tut.fin.spin': { zh: '旋轉終結', en: 'Spin Finish' },
  'tut.fin.over': { zh: '場外終結', en: 'Over Finish' },
  'tut.fin.burst': { zh: '爆裂終結', en: 'Burst Finish' },
  'tut.fin.xtreme': { zh: '極限終結', en: 'Xtreme Finish' },
  'tut.pts': { zh: '{n} 分', en: '{n} pts' },
  'tut.pt': { zh: '{n} 分', en: '{n} pt' },
  'tut.toastRetry': { zh: '這次沒有拉條！再試一次', en: "You didn't pull the cord! Try again" },
  'tut.toastRestart': { zh: '被終結了！重來一次', en: 'You got finished! Try again' },
} as const satisfies Record<string, TextEntry>;

export type TextKey = keyof typeof TEXT;
